name: base16
description: Simple hex (base16) encoder
version: 1.0.0
author: Subbotin Aleksei <darkandjeweled@gmail.com>
homepage: https://github.com/Moonspeaker/hex

environment:
  sdk: ">=2.1.0 <3.0.0"

dev_dependencies:
  test: ^1.9.3