name: base16
description: Simple base16 (hex) encoder. Used to encode bytes to semi-readable String format, e.g. to encode bytes of UUID, ObjectID, etc.

version: 2.0.2
homepage: https://github.com/Moonspeaker/hex

environment:
  sdk: ">=2.3.0 <3.0.0"

dev_dependencies:
  test: